[options]
addons_path = C:\Program Files\Odoo 19.0.20260217\server\odoo\addons,C:\Users\HP\odoo-addons
db_host = localhost
db_port = 5432
db_name = messob_db
db_user = odoo
db_password = odoo
http_port = 8069
log_level = info
