[options]
admin_passwd = admin
db_host = localhost
db_port = 5432
db_user = odoo
db_password = odoo
db_name = messob_db
addons_path = C:\Program Files\Odoo 19.0.20260217\server\odoo\addons,C:\Users\HP\odoo-addons
data_dir = C:\Users\HP\odoo_dev\data
http_port = 8069
logfile = C:\Users\HP\odoo-addons\mesob_fleet_customizations\odoo.log
log_level = info
workers = 0
