from . import fleet_vehicle
from . import hr_employee
from . import service_record
from . import fuel_log
from . import odometer_log
from . import maintenance_schedule
from . import maintenance_log
from . import trip_request
from . import trip_assignment
from . import trip_log
from . import inventory_allocation
from . import gps_tracking
from . import fleet_analytics
from . import trip_assign_wizard
from . import pickup_update_wizard