from . import fleet_vehicle
from . import service_record
from . import odometer_log
from . import maintenance_schedule
from . import inventory_allocation
from . import trip_request
from . import trip_assignment
from . import trip_log
from . import fuel_log
from . import maintenance_log